version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
cache: C:\Users\appveyor\.dnx
build_script:
- cmd: >-
    cd ./SepidSystem.Connect

    dotnet restore

    dotnet pack -c release

    cd ..
 

deploy:
- provider: GitHub
  api_key: 
    secure: f2b61d86beb31aa573131e5c5747388700a64d11
  skip_symbols: true
notifications:
- provider: Email
  to:
  - arasoulian@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
environment:
  my_variable:
    secure: Aeo4uO5/SQnpGsD/dMsdrI3yvSKDKl9Eq/kkIEJFkNGoMU9NLIHxBW1eTOxW43Fv